---

# Yum
- name: yum install golang
  yum: pkg=golang state=latest
  when: ansible_pkg_mgr == 'yum'

# Homebrew
- name: brew install go
  homebrew: name=go state=installed
  become: true
  become_user: "{{ go_user }}"
  when: ansible_pkg_mgr == 'homebrew'
