---

# Homebrew
- name: Install dep (Homebrew)
  homebrew:
    name:
      - dep
    state: present
  become: true
  become_user: "{{ go_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew or Yum are supported)"
  when: ansible_pkg_mgr != 'homebrew'
